%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This is the main file of the AMIGO implementation of benchmark B2     
%
% - To change the optimization settings, edit lines 954-959, where the
% optimizer (default: eSS), local solver (default: fmincon), and maximum
% number of function evaluations and CPU time are set.
%
% - If you want to modify the parameter bounds and initial guess, modify
% lines 921-945. Note that when comparing optimization methods these 
% settings must be equal for all methods, to avoid unfair comparisons.
%
% - For further modifications please refer to the AMIGO manual and the
% benchmarks documentation.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%=======================================
% PATHS RELATED DATA 
%=======================================

inputs.plotd.plotlevel='noplot';
inputs.pathd.results_folder	= 'b2';
inputs.pathd.short_name		= 'b2';

%=======================================
% MODEL RELATED DATA 
%=======================================
inputs.model.input_model_type	= 'charmodelC';
inputs.nlpsol.nlpsolver			= 'ess';
inputs.model.n_st				= 18;
inputs.model.n_par				= 121;
inputs.model.n_stimulus			= 0;
inputs.model.exe_type           = 'standard';
inputs.ivpsol.ivpsolver         = 'cvodes';         
inputs.ivpsol.senssolver        = 'cvodes';       

inputs.model.st_names			= char( ...
									'cdhap', ...
									'ce4p', ...
									'cf6p', ...
									'cfdp', ...
									'cg1p', ...
									'cg6p', ...
									'cgap', ...
									'cpep', ...
									'cpg', ...
									'cpg2', ...
									'cpg3', ...
									'cpgp', ...
									'cpyr', ...
									'crib5p', ...
									'cribu5p', ...
									'csed7p', ...
									'cxyl5p', ...
									'cglcex' ...
									);

inputs.model.par_names			= char( ...
									'kALDOdhap', ...
									'kALDOeq', ...
									'kALDOfdp', ...
									'kALDOgap', ...
									'kALDOgapinh', ...
									'KDAHPSe4p', ...
									'KDAHPSpep', ...
									'KENOeq', ...
									'KENOpep', ...
									'KENOpg2', ...
									'KG1PATatp', ...
									'KG1PATfdp', ...
									'KG1PATg1p', ...
									'KG3PDHdhap', ...
									'KG6PDHg6p', ...
									'KG6PDHnadp', ...
									'KG6PDHnadphg6pinh', ...
									'KG6PDHnadphnadpinh', ...
									'KGAPDHeq', ...
									'KGAPDHgap', ...
									'KGAPDHnad', ...
									'KGAPDHnadh', ...
									'KGAPDHpgp', ...
									'KPDHpyr', ...
									'KpepCxylasefdp', ...
									'KpepCxylasepep', ...
									'KPFKadpa', ...
									'KPFKadpb', ...
									'KPFKadpc', ...
									'KPFKampa', ...
									'KPFKampb', ...
									'KPFKatps', ...
									'KPFKf6ps', ...
									'KPFKpep', ...
									'KPGDHatpinh', ...
									'KPGDHnadp', ...
									'KPGDHnadphinh', ...
									'KPGDHpg', ...
									'KPGIeq', ...
									'KPGIf6p', ...
									'KPGIf6ppginh', ...
									'KPGIg6p', ...
									'KPGIg6ppginh', ...
									'KPGKadp', ...
									'KPGKatp', ...
									'KPGKeq', ...
									'KPGKpg3', ...
									'KPGKpgp', ...
									'KPGluMueq', ...
									'KPGluMupg2', ...
									'KPGluMupg3', ...
									'KPGMeq', ...
									'KPGMg1p', ...
									'KPGMg6p', ...
									'KPKadp', ...
									'KPKamp', ...
									'KPKatp', ...
									'KPKfdp', ...
									'KPKpep', ...
									'KPTSa1', ...
									'KPTSa2', ...
									'KPTSa3', ...
									'KPTSg6p', ...
									'KR5PIeq', ...
									'KRPPKrib5p', ...
									'KRu5Peq', ...
									'KSerSynthpg3', ...
									'KSynth1pep', ...
									'KSynth2pyr', ...
									'KTAeq', ...
									'kTISdhap', ...
									'kTISeq', ...
									'kTISgap', ...
									'KTKaeq', ...
									'KTKbeq', ...
									'LPFK', ...
									'LPK', ...
									'nDAHPSe4p', ...
									'nDAHPSpep', ...
									'nG1PATfdp', ...
									'nPDH', ...
									'npepCxylasefdp', ...
									'nPFK', ...
									'nPK', ...
									'nPTSg6p', ...
									'rmaxALDO', ...
									'rmaxDAHPS', ...
									'rmaxENO', ...
									'rmaxG1PAT', ...
									'rmaxG3PDH', ...
									'rmaxG6PDH', ...
									'rmaxGAPDH', ...
									'rmaxMetSynth', ...
									'rmaxMurSynth', ...
									'rmaxPDH', ...
									'rmaxpepCxylase', ...
									'rmaxPFK', ...
									'rmaxPGDH', ...
									'rmaxPGI', ...
									'rmaxPGK', ...
									'rmaxPGluMu', ...
									'rmaxPGM', ...
									'rmaxPK', ...
									'rmaxPTS', ...
									'rmaxR5PI', ...
									'rmaxRPPK', ...
									'rmaxRu5P', ...
									'rmaxSerSynth', ...
									'rmaxSynth1', ...
									'rmaxSynth2', ...
									'rmaxTA', ...
									'rmaxTIS', ...
									'rmaxTKa', ...
									'rmaxTKb', ...
									'rmaxTrpSynth', ...
									'VALDOblf', ...
									'cfeed', ...
									'Dil', ...
									'mu', ...
									'cytosol', ...
									'extracellular' ...
									);

inputs.model.eqns			= ...
	char( ...
		'cadp			 = 0.582 + 1.73 * 2.731 ^ (-0.15 * t) * (0.12 * t + 0.000214 * t ^ 3)', ...
		'camp			 = 0.123 + 7.25 * (t / (7.25 + 1.47 * t + 0.17 * t ^ 2)) + 1.073 / (1.29 + 8.05 * t)', ...
		'catp			 = 4.27 - 4.163 * (t / (0.657 + 1.43 * t + 0.0364 * t ^ 2))', ...
		'cnad			 = 1.314 + 1.314 * 2.73 ^ (-0.0435 * t - 0.342) - (t + 7.871) * (2.73 ^ (-0.0218 * t - 0.171) / (8.481 + t))', ...
		'cnadh			 = 0.0934 + 0.00111 * 2.371 ^ (-0.123 * t) * (0.844 * t + 0.104 * t ^ 3)', ...
		'cnadp			 = 0.159 - 0.00554 * (t / (2.8 - 0.271 * t + 0.01 * t ^ 2)) + 0.182 / (4.82 + 0.526 * t)', ...
		'cnadph			 = 0.062 + 0.332 * 2.718 ^ (-0.464 * t) * (0.0166 * t ^ 1.58 + 0.000166 * t ^ 4.73 + 0.1312 * 10 ^ (-9) * t ^ 7.89 + 0.1362 * 10 ^ (-12) * t ^ 11 + 0.1233 * 10 ^ (-15) * t ^ 14.2)', ...
		'vALDO			 = cytosol * rmaxALDO * (cfdp - cgap * cdhap / kALDOeq) / (kALDOfdp + cfdp + kALDOgap * cdhap / (kALDOeq * VALDOblf) + kALDOdhap * cgap / (kALDOeq * VALDOblf) + cfdp * cgap / kALDOgapinh + cgap * cdhap / (VALDOblf * kALDOeq))', ...
		'vDAHPS			 = cytosol * rmaxDAHPS * ce4p ^ nDAHPSe4p * cpep ^ nDAHPSpep / ((KDAHPSe4p + ce4p ^ nDAHPSe4p) * (KDAHPSpep + cpep ^ nDAHPSpep))', ...
		'vDHAP			 = cytosol * mu * cdhap', ...
		'vE4P			 = cytosol * mu * ce4p', ...
		'vENO			 = cytosol * rmaxENO * (cpg2 - cpep / KENOeq) / (KENOpg2 * (1 + cpep / KENOpep) + cpg2)', ...
		'vEXTER			 = extracellular * Dil * (cfeed - cglcex)', ...
		'vG1PAT			 = cytosol * rmaxG1PAT * cg1p * catp * (1 + (cfdp / KG1PATfdp) ^ nG1PATfdp) / ((KG1PATatp + catp) * (KG1PATg1p + cg1p))', ...
		'vG3PDH			 = cytosol * rmaxG3PDH * cdhap / (KG3PDHdhap + cdhap)', ...
		'vG6P			 = cytosol * mu * cg6p', ...
		'vG6PDH			 = cytosol * rmaxG6PDH * cg6p * cnadp / ((cg6p + KG6PDHg6p) * (1 + cnadph / KG6PDHnadphg6pinh) * (KG6PDHnadp * (1 + cnadph / KG6PDHnadphnadpinh) + cnadp))', ...
		'vGAP			 = cytosol * mu * cgap', ...
		'vGAPDH			 = cytosol * rmaxGAPDH * (cgap * cnad - cpgp * cnadh / KGAPDHeq) / ((KGAPDHgap * (1 + cpgp / KGAPDHpgp) + cgap) * (KGAPDHnad * (1 + cnadh / KGAPDHnadh) + cnad))', ...
		'vGLP			 = cytosol * mu * cg1p', ...
		'vMURSyNTH		 = cytosol * rmaxMurSynth', ...
		'vMethSynth		 = cytosol * rmaxMetSynth', ...
		'vPDH			 = cytosol * rmaxPDH * cpyr ^ nPDH / (KPDHpyr + cpyr ^ nPDH)', ...
		'vPEP			 = cytosol * mu * cpep', ...
		'vPFK			 = cytosol * rmaxPFK * catp * cf6p / ((catp + KPFKatps * (1 + cadp / KPFKadpc)) * (cf6p + KPFKf6ps * (1 + cpep / KPFKpep + cadp / KPFKadpb + camp / KPFKampb) / (1 + cadp / KPFKadpa + camp / KPFKampa)) * (1 + LPFK / (1 + cf6p * (1 + cadp / KPFKadpa + camp / KPFKampa) / (KPFKf6ps * (1 + cpep / KPFKpep + cadp / KPFKadpb + camp / KPFKampb))) ^ nPFK))', ...
		'vPG			 = cytosol * mu * cpg', ...
		'vPG3			 = cytosol * mu * cpg3', ...
		'vPGDH			 = cytosol * rmaxPGDH * cpg * cnadp / ((cpg + KPGDHpg) * (cnadp + KPGDHnadp * (1 + cnadph / KPGDHnadphinh) * (1 + catp / KPGDHatpinh)))', ...
		'vPGI			 = cytosol * rmaxPGI * (cg6p - cf6p / KPGIeq) / (KPGIg6p * (1 + cf6p / (KPGIf6p * (1 + cpg / KPGIf6ppginh)) + cpg / KPGIg6ppginh) + cg6p)', ...
		'vPGK			 = cytosol * rmaxPGK * (cadp * cpgp - catp * cpg3 / KPGKeq) / ((KPGKadp * (1 + catp / KPGKatp) + cadp) * (KPGKpgp * (1 + cpg3 / KPGKpg3) + cpgp))', ...
		'vPGM			 = cytosol * rmaxPGM * (cg6p - cg1p / KPGMeq) / (KPGMg6p * (1 + cg1p / KPGMg1p) + cg6p)', ...
		'vPGP			 = cytosol * mu * cpgp', ...
		'vPK			 = cytosol * rmaxPK * cpep * (cpep / KPKpep + 1) ^ (nPK - 1) * cadp / (KPKpep * (LPK * ((1 + catp / KPKatp) / (cfdp / KPKfdp + camp / KPKamp + 1)) ^ nPK + (cpep / KPKpep + 1) ^ nPK) * (cadp + KPKadp))', ...
		'vPPK			 = cytosol * rmaxRPPK * crib5p / (KRPPKrib5p + crib5p)', ...
		'vPTS			 = extracellular * rmaxPTS * cglcex * (cpep / cpyr) / ((KPTSa1 + KPTSa2 * (cpep / cpyr) + KPTSa3 * cglcex + cglcex * (cpep / cpyr)) * (1 + cg6p ^ nPTSg6p / KPTSg6p))', ...
		'vR5PI			 = cytosol * rmaxR5PI * (cribu5p - crib5p / KR5PIeq)', ...
		'vRIB5P			 = cytosol * mu * crib5p', ...
		'vRibu5p		 = cytosol * mu * cribu5p', ...
		'vRu5P			 = cytosol * rmaxRu5P * (cribu5p - cxyl5p / KRu5Peq)', ...
		'vSED7P			 = cytosol * mu * csed7p', ...
		'vSynth1		 = cytosol * rmaxSynth1 * cpep / (KSynth1pep + cpep)', ...
		'vSynth2		 = cytosol * rmaxSynth2 * cpyr / (KSynth2pyr + cpyr)', ...
		'vTA			 = cytosol * rmaxTA * (cgap * csed7p - ce4p * cf6p / KTAeq)', ...
		'vTIS			 = cytosol * rmaxTIS * (cdhap - cgap / kTISeq) / (kTISdhap * (1 + cgap / kTISgap) + cdhap)', ...
		'vTKA			 = cytosol * rmaxTKa * (crib5p * cxyl5p - csed7p * cgap / KTKaeq)', ...
		'vTKB			 = cytosol * rmaxTKb * (cxyl5p * ce4p - cf6p * cgap / KTKbeq)', ...
		'vTRPSYNTH		 = cytosol * rmaxTrpSynth', ...
		'vXYL5P			 = cytosol * mu * cxyl5p', ...
		'vf6P			 = cytosol * mu * cf6p', ...
		'vfdP			 = cytosol * mu * cfdp', ...
		'vpepCxylase	 = cytosol * rmaxpepCxylase * cpep * (1 + (cfdp / KpepCxylasefdp) ^ npepCxylasefdp) / (KpepCxylasepep + cpep)', ...
		'vpg2			 = cytosol * mu * cpg2', ...
		'vpyr			 = cytosol * mu * cpyr', ...
		'vrpGluMu		 = cytosol * rmaxPGluMu * (cpg3 - cpg2 / KPGluMueq) / (KPGluMupg3 * (1 + cpg2 / KPGluMupg2) + cpg3)', ...
		'vsersynth		 = cytosol * rmaxSerSynth * cpg3 / (KSerSynthpg3 + cpg3)', ...
		'dcdhap			 = (vALDO - vDHAP - vG3PDH - vTIS)/cytosol', ...
		'dce4p			 = (- vDAHPS - vE4P + vTA - vTKB)/cytosol', ...
		'dcf6p			 = (- 2.0 * vMURSyNTH - vPFK + vPGI + vTA + vTKB - vf6P)/cytosol', ...
		'dcfdp			 = (- vALDO + vPFK - vfdP)/cytosol', ...
		'dcg1p			 = (- vG1PAT - vGLP + vPGM)/cytosol', ...
		'dcg6p			 = (- vG6P - vG6PDH - vPGI - vPGM + 65.0 * vPTS)/cytosol', ...
		'dcgap			 = (vALDO - vGAP - vGAPDH - vTA + vTIS + vTKA + vTKB + vTRPSYNTH)/cytosol', ...
		'dcpep			 = (- vDAHPS + vENO - vPEP - vPK - 65.0 * vPTS - vSynth1 - vpepCxylase)/cytosol', ...
		'dcpg			 = (vG6PDH - vPG - vPGDH)/cytosol', ...
		'dcpg2			 = (- vENO - vpg2 + vrpGluMu)/cytosol', ...
		'dcpg3			 = (- vPG3 + vPGK - vrpGluMu - vsersynth)/cytosol', ...
		'dcpgp			 = (vGAPDH - vPGK - vPGP)/cytosol', ...
		'dcpyr			 = (vMethSynth - vPDH + vPK + 65.0 * vPTS - vSynth2 + vTRPSYNTH - vpyr)/cytosol', ...
		'dcrib5p		 = (- vPPK + vR5PI - vRIB5P - vTKA)/cytosol', ...
		'dcribu5p		 = (vPGDH - vR5PI - vRibu5p - vRu5P)/cytosol', ...
		'dcsed7p		 = (- vSED7P - vTA + vTKA)/cytosol', ...
		'dcxyl5p		 = (vRu5P - vTKA - vTKB - vXYL5P)/cytosol', ...
		'dcglcex		 = (vEXTER - vPTS)/extracellular' ...
		);

% Nominal values of the 116 unknown parameters:
kALDOdhap						= 0.088;
kALDOeq							= 0.144;
kALDOfdp						= 1.75;
kALDOgap						= 0.088;
kALDOgapinh						= 0.6;
KDAHPSe4p						= 0.035;
KDAHPSpep						= 0.0053;
KENOeq							= 6.73;
KENOpep							= 0.135;
KENOpg2							= 0.1;
KG1PATatp						= 4.42;
KG1PATfdp						= 0.119;
KG1PATg1p						= 3.2;
KG3PDHdhap						= 1;
KG6PDHg6p						= 14.4;
KG6PDHnadp						= 0.0246;
KG6PDHnadphg6pinh				= 6.43;
KG6PDHnadphnadpinh				= 0.01;
KGAPDHeq						= 0.63;
KGAPDHgap						= 0.683;
KGAPDHnad						= 0.252;
KGAPDHnadh						= 1.09;
KGAPDHpgp						= 1.04e-05;
KPDHpyr							= 1159;
KpepCxylasefdp					= 0.7;
KpepCxylasepep					= 4.07;
KPFKadpa						= 128;
KPFKadpb						= 3.89;
KPFKadpc						= 4.14;
KPFKampa						= 19.1;
KPFKampb						= 3.2;
KPFKatps						= 0.123;
KPFKf6ps						= 0.325;
KPFKpep							= 3.26;
KPGDHatpinh						= 208;
KPGDHnadp						= 0.0506;
KPGDHnadphinh					= 0.0138;
KPGDHpg							= 37.5;
KPGIeq							= 0.1725;
KPGIf6p							= 0.266;
KPGIf6ppginh					= 0.2;
KPGIg6p							= 2.9;
KPGIg6ppginh					= 0.2;
KPGKadp							= 0.185;
KPGKatp							= 0.653;
KPGKeq							= 1934.4;
KPGKpg3							= 0.473;
KPGKpgp							= 0.0468;
KPGluMueq						= 0.188;
KPGluMupg2						= 0.369;
KPGluMupg3						= 0.2;
KPGMeq							= 0.196;
KPGMg1p							= 0.0136;
KPGMg6p							= 1.038;
KPKadp							= 0.26;
KPKamp							= 0.2;
KPKatp							= 22.5;
KPKfdp							= 0.19;
KPKpep							= 0.31;
KPTSa1							= 3082.3;
KPTSa2							= 0.01;
KPTSa3							= 245.3;
KPTSg6p							= 2.15;
KR5PIeq							= 4;
KRPPKrib5p						= 0.1;
KRu5Peq							= 1.4;
KSerSynthpg3					= 1;
KSynth1pep						= 1;
KSynth2pyr						= 1;
KTAeq							= 1.05;
kTISdhap						= 2.8;
kTISeq							= 1.39;
kTISgap							= 0.3;
KTKaeq							= 1.2;
KTKbeq							= 10;
LPFK							= 5.62907e+06;
LPK								= 1000;
nDAHPSe4p						= 2.6;
nDAHPSpep						= 2.2;
nG1PATfdp						= 1.2;
nPDH							= 3.68;
npepCxylasefdp					= 4.21;
nPFK							= 11.1;
nPK								= 4;
nPTSg6p							= 3.66;
rmaxALDO						= 17.4146;
rmaxDAHPS						= 0.107953;
rmaxENO							= 330.448;
rmaxG1PAT						= 0.00752546;
rmaxG3PDH						= 0.0116204;
rmaxG6PDH						= 1.3802;
rmaxGAPDH						= 921.594;
rmaxMetSynth					= 0.0022627;
rmaxMurSynth					= 0.00043711;
rmaxPDH							= 6.05953;
rmaxpepCxylase					= 0.107021;
rmaxPFK							= 1840.58;
rmaxPGDH						= 16.2324;
rmaxPGI							= 650.988;
rmaxPGK							= 3021.77;
rmaxPGluMu						= 89.0497;
rmaxPGM							= 0.839824;
rmaxPK							= 0.0611315;
rmaxPTS							= 7829.78;
rmaxR5PI						= 4.83841;
rmaxRPPK						= 0.0129005;
rmaxRu5P						= 6.73903;
rmaxSerSynth					= 0.0257121;
rmaxSynth1						= 0.019539;
rmaxSynth2						= 0.0736186;
rmaxTA							= 10.8716;
rmaxTIS							= 68.6747;
rmaxTKa							= 9.47338;
rmaxTKb							= 86.5586;
rmaxTrpSynth					= 0.001037;
VALDOblf						= 2;

% Nominal values of the 5 known parameters:
cfeed							= 110.96;
Dil								= 2.78e-05;
mu								= 2.78e-05;
cytosol							= 1;
extracellular					= 1;

% Nominal parameter vector (121 parameters, known & unknown):
inputs.model.par				= [ ...
									kALDOdhap, ...
									kALDOeq, ...
									kALDOfdp, ...
									kALDOgap, ...
									kALDOgapinh, ...
									KDAHPSe4p, ...
									KDAHPSpep, ...
									KENOeq, ...
									KENOpep, ...
									KENOpg2, ...
									KG1PATatp, ...
									KG1PATfdp, ...
									KG1PATg1p, ...
									KG3PDHdhap, ...
									KG6PDHg6p, ...
									KG6PDHnadp, ...
									KG6PDHnadphg6pinh, ...
									KG6PDHnadphnadpinh, ...
									KGAPDHeq, ...
									KGAPDHgap, ...
									KGAPDHnad, ...
									KGAPDHnadh, ...
									KGAPDHpgp, ...
									KPDHpyr, ...
									KpepCxylasefdp, ...
									KpepCxylasepep, ...
									KPFKadpa, ...
									KPFKadpb, ...
									KPFKadpc, ...
									KPFKampa, ...
									KPFKampb, ...
									KPFKatps, ...
									KPFKf6ps, ...
									KPFKpep, ...
									KPGDHatpinh, ...
									KPGDHnadp, ...
									KPGDHnadphinh, ...
									KPGDHpg, ...
									KPGIeq, ...
									KPGIf6p, ...
									KPGIf6ppginh, ...
									KPGIg6p, ...
									KPGIg6ppginh, ...
									KPGKadp, ...
									KPGKatp, ...
									KPGKeq, ...
									KPGKpg3, ...
									KPGKpgp, ...
									KPGluMueq, ...
									KPGluMupg2, ...
									KPGluMupg3, ...
									KPGMeq, ...
									KPGMg1p, ...
									KPGMg6p, ...
									KPKadp, ...
									KPKamp, ...
									KPKatp, ...
									KPKfdp, ...
									KPKpep, ...
									KPTSa1, ...
									KPTSa2, ...
									KPTSa3, ...
									KPTSg6p, ...
									KR5PIeq, ...
									KRPPKrib5p, ...
									KRu5Peq, ...
									KSerSynthpg3, ...
									KSynth1pep, ...
									KSynth2pyr, ...
									KTAeq, ...
									kTISdhap, ...
									kTISeq, ...
									kTISgap, ...
									KTKaeq, ...
									KTKbeq, ...
									LPFK, ...
									LPK, ...
									nDAHPSe4p, ...
									nDAHPSpep, ...
									nG1PATfdp, ...
									nPDH, ...
									npepCxylasefdp, ...
									nPFK, ...
									nPK, ...
									nPTSg6p, ...
									rmaxALDO, ...
									rmaxDAHPS, ...
									rmaxENO, ...
									rmaxG1PAT, ...
									rmaxG3PDH, ...
									rmaxG6PDH, ...
									rmaxGAPDH, ...
									rmaxMetSynth, ...
									rmaxMurSynth, ...
									rmaxPDH, ...
									rmaxpepCxylase, ...
									rmaxPFK, ...
									rmaxPGDH, ...
									rmaxPGI, ...
									rmaxPGK, ...
									rmaxPGluMu, ...
									rmaxPGM, ...
									rmaxPK, ...
									rmaxPTS, ...
									rmaxR5PI, ...
									rmaxRPPK, ...
									rmaxRu5P, ...
									rmaxSerSynth, ...
									rmaxSynth1, ...
									rmaxSynth2, ...
									rmaxTA, ...
									rmaxTIS, ...
									rmaxTKa, ...
									rmaxTKb, ...
									rmaxTrpSynth, ...
									VALDOblf, ...
									cfeed, ...
									Dil, ...
									mu, ...
									cytosol, ...
									extracellular ...
									];

                                
%========== Extra =========
inputs.model.AMIGOjac = 0;
inputs.model.AMIGOsensrhs=1;
                                
%=======================================
% EXPERIMENTAL SCHEME RELATED DATA 
%=======================================

% Experimental data were obtained from a single experiment. However, 5 
% different sets of measurement times were used in that experiment (i.e. 
% different states were measured at different timepoints). Since in AMIGO 
% all the measured quantities in a experiment have to be measured at the 
% same instants, we must define 5 different experiments:
inputs.exps.n_exp				= 5;
inputs.exps.data_type			= 'real';
inputs.exps.noise_type			= 'homo_var';

% Initial concentrations of the 18 states:
cdhap_init						= 0.167;
ce4p_init						= 0.098;
cpg2_init						= 0.399;
cpg3_init						= 2.13;
cpgp_init						= 0.008;
crib5p_init						= 0.398;
cribu5p_init					= 0.111;
csed7p_init						= 0.276;
cxyl5p_init						= 0.138;
cf6p_init						= 0.6;
cfdp_init						= 0.272;
cg1p_init						= 0.653;
cg6p_init						= 3.48;
cgap_init						= 0.218;
cglcex_init						= 2;
cpep_init						= 2.67;
cpg_init						= 0.808;
cpyr_init						= 2.67;

y0								= zeros(1, 18);
y0(1)							= cdhap_init;
y0(2)							= ce4p_init;
y0(3)							= cf6p_init;
y0(4)							= cfdp_init;
y0(5)							= cg1p_init;
y0(6)							= cg6p_init;
y0(7)							= cgap_init;
y0(8)							= cpep_init;
y0(9)							= cpg_init;
y0(10)							= cpg2_init;
y0(11)							= cpg3_init;
y0(12)							= cpgp_init;
y0(13)							= cpyr_init;
y0(14)							= crib5p_init;
y0(15)							= cribu5p_init;
y0(16)							= csed7p_init;
y0(17)							= cxyl5p_init;
y0(18)							= cglcex_init;

for index = 1:inputs.exps.n_exp
	inputs.exps.exp_y0{index} = y0;
end

%=======================================
% EXPERIMENTAL DATA 1: cpep, cg6p, cpyr, cf6p
%=======================================

inputs.exps.n_obs{1}			= 4;
inputs.exps.obs_names{1}		= char('cpep_obs', 'cg6p_obs', 'cpyr_obs', 'cf6p_obs');
inputs.exps.obs{1}				= char('cpep_obs = cpep', 'cg6p_obs = cg6p', 'cpyr_obs = cpyr', 'cf6p_obs = cf6p');
inputs.exps.n_s{1}				= 14;
inputs.exps.t_f{1}				= 300.5;
inputs.exps.t_con{1}			= [0, 300.5];
inputs.exps.u{1}				= 1;
inputs.exps.u_interp{1}			= 'sustained';

inputs.exps.t_s{1}				= [ ...
									0.15;
									0.3;
									0.45;
									0.6;
									0.8;
									5.5;
									12;
									21.5;
									31.5;
									61;
									90;
									120.5;
									180.5;
									300.5;
									]';

inputs.exps.exp_data{1}			= [ ...
									1.99,	4.39,	4.07,	0.62;
									2.1,	4.76,	3.71,	0.66;
									2.09,	4.86,	3.19,	0.74;
									1.84,	4.65,	3.57,	0.62;
									2.31,	4.75,	3.14,	0.75;
									2.76,	5.52,	2.38,	0.92;
									3.05,	5.86,	3.71,	1.15;
									2.42,	4.39,	3.19,	0.57;
									2.23,	3.6,	5.24,	0.46;
									2.52,	3.83,	4.47,	0.57;
									2.81,	4.3,	3.62,	0.57;
									2.71,	4.05,	3.62,	0.69;
									2.71,	3.27,	2.86,	0.46;
									2.7,	3.38,	2.4,	0.46;
									];

%=======================================
% EXPERIMENTAL DATA 2: cglcex
%=======================================

inputs.exps.n_obs{2}			= 1;
inputs.exps.obs_names{2}		= char('cglcex_obs');
inputs.exps.obs{2}				= char('cglcex_obs = cglcex');
inputs.exps.n_s{2}				= 11;
inputs.exps.t_f{2}				= 301;
inputs.exps.t_con{2}			= [0, 301];
inputs.exps.u{2}				= 1;
inputs.exps.u_interp{2}			= 'sustained';

inputs.exps.t_s{2}				= [ ...
									5.5;
									13.5;
									31;
									61;
									91;
									151;
									181;
									212.5;
									241;
									270.5;
									301;
									]';

inputs.exps.exp_data{2}			= [ ...
									1.255555556;
									1.311111111;
									1.283333333;
									0.8611111111;
									0.5972222223;
									0.09611111112;
									0.04333333334;
									0.05055555556;
									0.04777777778;
									0.04777777778;
									0.06;
									];

%=======================================
% EXPERIMENTAL DATA 3: cg1p
%=======================================

inputs.exps.n_obs{3}			= 1;
inputs.exps.obs_names{3}		= char('cg1p_obs');
inputs.exps.obs{3}				= char('cg1p_obs = cg1p');
inputs.exps.n_s{3}				= 8;
inputs.exps.t_f{3}				= 299;
inputs.exps.t_con{3}			= [0, 299];
inputs.exps.u{3}				= 1;
inputs.exps.u_interp{3}			= 'sustained';

inputs.exps.t_s{3}				= [ ...
									2;
									16;
									19;
									31;
									57;
									91.5;
									150.5;
									299;
									]';

inputs.exps.exp_data{3}			= [ ...
									1.35;
									0.83;
									0.83;
									0.78;
									0.84;
									0.64;
									0.74;
									0.70;
									];

%=======================================
% EXPERIMENTAL DATA 4: cpg
%=======================================

inputs.exps.n_obs{4}			= 1;
inputs.exps.obs_names{4}		= char('cpg_obs');
inputs.exps.obs{4}				= char('cpg_obs = cpg');
inputs.exps.n_s{4}				= 15;
inputs.exps.t_f{4}				= 209;
inputs.exps.t_con{4}			= [0, 209];
inputs.exps.u{4}				= 1;
inputs.exps.u_interp{4}			= 'sustained';

inputs.exps.t_s{4}				= [ ...
									3.5;
									4;
									12;
									12.25;
									21;
									25.75;
									30;
									32.25;
									58.5;
									59;
									119.75;
									124;
									178;
									180;
									209;
									]';

inputs.exps.exp_data{4}			= [ ...
									1.01;
									0.92;
									1.15;
									1.19;
									1.06;
									1.10;
									1.05;
									1.08;
									0.97;
									1.01;
									0.92;
									0.89;
									0.74;
									0.88;
									0.80;
									];

%=======================================
% EXPERIMENTAL DATA 5: cfdp, cgap
%=======================================

inputs.exps.n_obs{5}			= 2;
inputs.exps.obs_names{5}		= char('cfdp_obs', 'cgap_obs');
inputs.exps.obs{5}				= char('cfdp_obs = cfdp', 'cgap_obs = cgap');
inputs.exps.n_s{5}				= 10;
inputs.exps.t_f{5}				= 300;
inputs.exps.t_con{5}			= [0, 300];
inputs.exps.u{5}				= 1;
inputs.exps.u_interp{5}			= 'sustained';

inputs.exps.t_s{5}				= [ ...
									4.5;
									11;
									20;
									30;
									60;
									90;
									119.5;
									180;
									239.5;
									300;
									]';

inputs.exps.exp_data{5}			= [ ...
									0.19,	0.28;
									0.56,	0.32;
									1,	0.31;
									2.83,	0.24;
									1.5,	0.30;
									2.26,	0.18;
									2.4,	0.22;
									1.25,	0.21;
									0.07,	0.22;
									0.02,	0.20;
									];
                                
                                
   
%=======================================                                
% Error data, all experiments:
%=======================================
                                
for i=1:inputs.exps.n_exp
    inputs.exps.error_data{i} = 0.15*inputs.exps.exp_data{i};
end
                                
                                
%=======================================
% UNKNOWNS RELATED DATA 
%=======================================

% The model has 116 unknown parameters and 5 known parameters.
% Names of the 116 unknown parameters:
inputs.PEsol.id_global_theta	= char( ...
									'kALDOdhap', ...
									'kALDOeq', ...
									'kALDOfdp', ...
									'kALDOgap', ...
									'kALDOgapinh', ...
									'KDAHPSe4p', ...
									'KDAHPSpep', ...
									'KENOeq', ...
									'KENOpep', ...
									'KENOpg2', ...
									'KG1PATatp', ...
									'KG1PATfdp', ...
									'KG1PATg1p', ...
									'KG3PDHdhap', ...
									'KG6PDHg6p', ...
									'KG6PDHnadp', ...
									'KG6PDHnadphg6pinh', ...
									'KG6PDHnadphnadpinh', ...
									'KGAPDHeq', ...
									'KGAPDHgap', ...
									'KGAPDHnad', ...
									'KGAPDHnadh', ...
									'KGAPDHpgp', ...
									'KPDHpyr', ...
									'KpepCxylasefdp', ...
									'KpepCxylasepep', ...
									'KPFKadpa', ...
									'KPFKadpb', ...
									'KPFKadpc', ...
									'KPFKampa', ...
									'KPFKampb', ...
									'KPFKatps', ...
									'KPFKf6ps', ...
									'KPFKpep', ...
									'KPGDHatpinh', ...
									'KPGDHnadp', ...
									'KPGDHnadphinh', ...
									'KPGDHpg', ...
									'KPGIeq', ...
									'KPGIf6p', ...
									'KPGIf6ppginh', ...
									'KPGIg6p', ...
									'KPGIg6ppginh', ...
									'KPGKadp', ...
									'KPGKatp', ...
									'KPGKeq', ...
									'KPGKpg3', ...
									'KPGKpgp', ...
									'KPGluMueq', ...
									'KPGluMupg2', ...
									'KPGluMupg3', ...
									'KPGMeq', ...
									'KPGMg1p', ...
									'KPGMg6p', ...
									'KPKadp', ...
									'KPKamp', ...
									'KPKatp', ...
									'KPKfdp', ...
									'KPKpep', ...
									'KPTSa1', ...
									'KPTSa2', ...
									'KPTSa3', ...
									'KPTSg6p', ...
									'KR5PIeq', ...
									'KRPPKrib5p', ...
									'KRu5Peq', ...
									'KSerSynthpg3', ...
									'KSynth1pep', ...
									'KSynth2pyr', ...
									'KTAeq', ...
									'kTISdhap', ...
									'kTISeq', ...
									'kTISgap', ...
									'KTKaeq', ...
									'KTKbeq', ...
									'LPFK', ...
									'LPK', ...
									'nDAHPSe4p', ...
									'nDAHPSpep', ...
									'nG1PATfdp', ...
									'nPDH', ...
									'npepCxylasefdp', ...
									'nPFK', ...
									'nPK', ...
									'nPTSg6p', ...
									'rmaxALDO', ...
									'rmaxDAHPS', ...
									'rmaxENO', ...
									'rmaxG1PAT', ...
									'rmaxG3PDH', ...
									'rmaxG6PDH', ...
									'rmaxGAPDH', ...
									'rmaxMetSynth', ...
									'rmaxMurSynth', ...
									'rmaxPDH', ...
									'rmaxpepCxylase', ...
									'rmaxPFK', ...
									'rmaxPGDH', ...
									'rmaxPGI', ...
									'rmaxPGK', ...
									'rmaxPGluMu', ...
									'rmaxPGM', ...
									'rmaxPK', ...
									'rmaxPTS', ...
									'rmaxR5PI', ...
									'rmaxRPPK', ...
									'rmaxRu5P', ...
									'rmaxSerSynth', ...
									'rmaxSynth1', ...
									'rmaxSynth2', ...
									'rmaxTA', ...
									'rmaxTIS', ...
									'rmaxTKa', ...
									'rmaxTKb', ...
									'rmaxTrpSynth', ...
									'VALDOblf' ...
									);

% Nominal values of the 116 unknown parameters:
theta	 = inputs.model.par(1:116);

% The initial guess for the parameter vector is the nominal vector:
inputs.PEsol.global_theta_guess	= theta;

% Parameter bounds are usually 10 times larger / smaller than the nominal
% values...
inputs.PEsol.global_theta_min	= theta/10;
inputs.PEsol.global_theta_max	= theta*10;

% ... with the exception of the Hill coefficients, which have values
% between 1 and 12:
inputs.PEsol.global_theta_min(78)	= 1;
inputs.PEsol.global_theta_max(78)	= 12;
inputs.PEsol.global_theta_min(79)	= 1;
inputs.PEsol.global_theta_max(79)	= 12;
inputs.PEsol.global_theta_min(80)	= 1;
inputs.PEsol.global_theta_max(80)	= 12;
inputs.PEsol.global_theta_min(81)	= 1;
inputs.PEsol.global_theta_max(81)	= 12;
inputs.PEsol.global_theta_min(82)	= 1;
inputs.PEsol.global_theta_max(82)	= 12;
inputs.PEsol.global_theta_min(83)	= 1;
inputs.PEsol.global_theta_max(83)	= 12;
inputs.PEsol.global_theta_min(84)	= 1;
inputs.PEsol.global_theta_max(84)	= 12;
inputs.PEsol.global_theta_min(85)	= 1;
inputs.PEsol.global_theta_max(85)	= 12;

inputs.PEsol.PEcost_type = 'llk';
inputs.PEsol.llk_type = 'hetero';

%=======================================
% OPTIMIZATION settings
%=======================================

inputs.nlpsol.nlpsolver   = 'ess';
inputs.nlpsol.eSS.maxeval = 1.5e5;
inputs.nlpsol.eSS.maxtime = 3*3600;
% inputs.nlpsol.eSS.log_var = 1:(size(inputs.PEsol.global_theta_guess,2)); % set log exploration to all or selected vars
inputs.nlpsol.eSS.local.solver = 'fmincon';
inputs.nlpsol.eSS.local.finish = 'fmincon';
